#!/bin/bash
CONTROL_BOT=$0
path=$2
if [[ -n "$path" ]]; then
   cd $path
fi
BOT_FILE=$(cat tostart.txt)

case "$1" in
    start)
        if [ -e bot.pid ]; then
            if ( kill -0 $(cat bot.pid) 2> /dev/null ); then
                echo "Bot is already running"
                exit 2
            else
                echo "bot.pid found, but no bot running"
                echo "Possibly bot crashed"
                rm bot.pid
            fi
        fi
        echo "Starting bot"
        venv/bin/python3 $BOT_FILE >> log/bot.log 2>&1 &
        PID=$!
        if ( kill -0 $PID 2> /dev/null ); then
            echo $PID > bot.pid
            echo "Bot started"
        else
            echo "Bot could not start"
            exit 1
        fi
    ;;
    stop)
        if [ -e bot.pid ]; then
            echo "Stopping bot"
            if ( kill -TERM $(cat bot.pid) 2> /dev/null ); then
                c=1
                while [ "$c" -le 300 ]; do
                    if ( kill -0 $(cat bot.pid) 2> /dev/null ); then
                        echo -n "."
                        sleep 1
                    else
                        break
                    fi
                    c=$(($c+1)) 
                done
            fi
            if ( kill -0 $(cat bot.pid) 2> /dev/null ); then
                echo "Bot is not shutting down - killing"
                kill -KILL $(cat bot.pid)
            else
                echo "done"
            fi
            rm bot.pid
        else
            echo "No bot running (bot.pid is missing)"
            exit 2
        fi
    ;;
    status)
        if [ -e bot.pid ]; then
            if ( kill -0 $(cat bot.pid) 2> /dev/null ); then
                echo "Bot is running"
                exit 4
            else
                echo "Bot is dead"
                exit 5
            fi
        else
            echo "No bot running (bot.pid is missing)"
            exit 5
        fi
    ;;
    *)
        echo "Usage: ${0} {start|stop|status}"
        exit 3
esac
exit 0
