#!/bin/bash
if [ -f main.pid ]
then
pid=$(cat main.pid)
target=$(cat tostart.txt)
target=$(echo $pid $target)
file=$(ps aux | grep $pid | grep -v grep | awk '{print $2,$12}')
if [ "$target" = "$file" ]
then
echo "process exist"
exit 0
else
echo "process does not exist"
rm main.pid
exit 1
fi
else
echo "process does not exist"
exit 1
fi